name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build

      - name: Upload build outpus (APKs)
        uses: actions/upload-artifact@v2
        with:
            name: build-outputs
            path: app/build/outputs